# ==================== #
# Fuzzel Configuration #
# ==================== #

# General options
font=AnnotationM NF ExtraBold:size=14
prompt=">> "
icons-enabled=yes
fields=name,generic,comment,categories,filename,keywords
show-actions=yes
lines=10
width=32
horizontal-pad=20
vertical-pad=12
inner-pad=8
layer=overlay
exit-on-keyboard-focus-loss=yes

# Gruvbox theme
[colors]
background=#1d2021a0
text=#d4be98ff
match=#a9b665ff
selection-match=#d3869bff
selection=#89b48240
selection-text=#ea6962ff
prompt=#7daea3ff
border=#7daea3ff

[border]
width=2
radius=12
